### PR TITLE
updating admin notice function

### PR DESCRIPTION
**Pull request by norcross**
the plugin had a very old method of checking for and displaying the admin notice. this updates that, along with two other minor fixes.

### CODE REVIEW

**Comment by splorp** [comment]
Hey Andrew!

I tested this branch on one of my WP 5.3.2 installs and didn’t notice anything odd.

We should probably bump the version number to 1.0.1 and add this to the read me.

**Review by splorp — CHANGES_REQUESTED** [review]
I tested this branch on one of my WP 5.3.2 installs and didn’t notice anything odd. Everything works, but we should probably bump the version number to 1.0.1 and add this update to the read me as part of the patch.

**Comment by norcross** [comment]
i usually update the readme and version on a small commit to `master` after my PR

**Review by norcross — COMMENTED** [review]
i usually update the readme and version on a small commit to master after my PR, which i will do in this case.

**Pull request merged**
